### ISSUE TITLE
Understand the results

### ISSUE THREAD

**Issue by zznx** [dayoonkwon/BioAge#21]
Hi, can you explain the difference between the two? Make it easy for me to understand.
```
"KDM\nBiological Age",
"Levine\nPhenotypic Age",
```
```
"Modified-KDM\nBiological Age",
"Modified-Levine\nPhenotypic Age"
```

I wonder if the two results are the same?
phenoage = phenoage_nhanes(biomarkers=c("albumin","alp","lncrp","totchol","lncreat","hba1c","sbp","bun","uap","lymph","mcv","wbc"))
phenoage = phenoage_nhanes(biomarkers=c("albumin_gL","alp","lncrp","totchol","lncreat_umol","hba1c","sbp","bun","uap","lymph","mcv","wbc"))

```
phenoage_nhanes = function(biomarkers) {

  #develop training dataset for Levine's phenoage method
  train = phenoage_calc(data = NHANES3 %>%
                          filter(age >= 20 & age <= 84) %>%
                          mutate(albumin = albumin_gL,
                                 glucose = glucose_mmol,
                                 creat = creat_umol,
                                 lncreat = lncreat_umol),
                        biomarkers, fit=NULL)
```

Should it be changed to this?
```
phenoage_nhanes = function(biomarkers) {

  #develop training dataset for Levine's phenoage method
  train = phenoage_calc(data = NHANES3 %>%
                          filter(age >= 20 & age <= 84),
                        biomarkers, fit=NULL)
```

**Comment by dayoonkwon** [comment]
For the first question, please read [this paper](https://doi.org/10.1007/s11357-021-00480-5) or I also stated in the readme file that what kdm0 and phenoage0 are. 

For the second question, if you want to use the same units as in the original code, then you can use the phenoage_nhanes. Yes, those two results are the same. But, if you prefer to use different units, then you can use phoenoage_calc to do so.
