### ISSUE TITLE
Is the original Phenotypic Age equation from Levine what you want?

### ISSUE THREAD

**Issue by rseiter** [dayoonkwon/BioAge#22]
The denominator was corrected from 0.090165 to 0.09165 here:
https://journals.plos.org/plosmedicine/article?id=10.1371/journal.pmed.1002760
It seems like a small difference, but changed my age estimates by almost two years.

Thank you for making the BioAge package available!

Regards,
Rich Seiter

**Comment by dayoonkwon** [comment]
Done. Thank you.
