### ISSUE TITLE
kdm_calc update?

### ISSUE THREAD

**Issue by qu515** [dayoonkwon/BioAge#23]
Hi Dayoon, I noticed that there was an update to the kdm_calc function 3 weeks ago. My kdm results became markedly different after the update with a lot more negative values, even though my code did not change. Upon checking the R file for kdm_calc, the main change in the update seems to concern the following line:

<img width="1060" alt="Screen Shot 2023-10-05 at 11 55 12 AM" src="https://github.com/dayoonkwon/BioAge/assets/122990988/417ac0f0-343f-4fc8-9706-2caf3ad469c6">

Could you elaborate on what this update is? Thank you for all your work!

**Comment by dayoonkwon** [comment]
Sorry for the confusion. I put it back to original form ` s_r = ((1-(rchar^2))/(rchar^2))*(((age_range[2]-age_range[1])^2)/(12*nrow(agev)))` 3 weeks ago.  Can you update your package again?

**Comment by dayoonkwon** [comment]
Sorry for the confusion. I put it back to original form `s_r = ((1-(rchar^2))/(rchar^2))*(((age_range[2]-age_range[1])^2)/(12*nrow(agev)))` 3 weeks ago. Can you update your package again?
