### ISSUE TITLE
kdm0 and phenoage0

### ISSUE THREAD

**Issue by qu515** [dayoonkwon/BioAge#24]
Hello Dayoon, very sorry to bother you, but I'm trying to replicate the kdm0 and phenoage0 values from the NHANES4 file that you provided, which I know are the original kdm/phenoage by Levine. For kdm, I've tried 
```
kdm = kdm_nhanes(biomarkers=c("fev","sbp","totchol","hba1c","albumin","creat","lncrp","alp","bun"))
```
and also
```
train = kdm_calc(NHANES3, biomarkers = c("fev","sbp","totchol","hba1c","albumin","creat","lncrp","alp","bun"))
kdm = kdm_calc(NHANES4, biomarkers = c("fev","sbp","totchol","hba1c","albumin","creat","lncrp","alp","bun"), fit = train$fit, s_ba2 = train$fit$s_ba2)
```
but the results are not the same as what you calculated. May I ask what's the code you implemented to calculate the kdm0 and phenoage0 values? Thank you again for all your replies!

**Comment by dayoonkwon** [comment]
Replicating the exact values using those functions might not be directly achievable due to the differences in the datasets. kdm0 and phenoage0 values were computed based on the published coefficients by Levine and colleagues (Levine et al, 2013 and 2018).
