### ISSUE TITLE
Enhancement Request: Flexible Column Naming for Age in kdm_calc Function

### ISSUE THREAD

**Issue by KaishinShaw** [dayoonkwon/BioAge#31]
Dear BioAge Developers,

I hope this message finds you well. I would like to suggest a minor enhancement to the `kdm_calc` function in the BioAge package, which could improve its usability. 

While reviewing the source code, specifically at `BioAge/R/kdm_calc.R` on line 64:

```R
survey::svyglm(form(marker, "age"), ...
```

I noticed that the column name for age data is hardcoded as 'age'. This requirement is not mentioned in the manual/documentation of the function, which might lead to confusion or errors for users with datasets having different column names for age.

Certainly, the BioAge package has achieved more comprehensive functionality compared to the older 'bjb40/bioage' project. However, I would recommend considering an implementation similar to what is found in the bjb40 project. Specifically, it would be beneficial to allow users to specify the column name for age data. An example modification could be:

```R
\item{agevar}{A character vector (length=1) indicating the name of the variable for age.}
```

This small enhancement could significantly increase the flexibility and user-friendliness of the `kdm_calc` function.

Thank you for your continuous efforts in developing and maintaining the BioAge package. Your work is greatly appreciated in the community!

Best regards,
Kaishin Shaw

**Comment by dayoonkwon** [comment]
Thank you for taking the time to delve into the BioAge package's code. I will take your recommendation into account and work towards incorporating this feature into the next update. Please stay tuned for future releases, and we hope that you will continue to find the BioAge package a useful asset in your research endeavors.
