### ISSUE TITLE
Request for data

### ISSUE THREAD

**Issue by manojvaithilingam** [dayoonkwon/BioAge#32]
Hi there,
Thanks a lot for sharing this - super awesome work! Was just wondering, did you have a sample dataset I could potentially use (without asking CALERIE themselves)? I was trying to see if I could somehow come up with the values used to re-create the KDM formula but wasn't sure how to (e.g. obtaining root mean squares for albumin). Would be grateful if possible! Thanks!

**Comment by dayoonkwon** [comment]
We cannot share the CALERIE data. But you can apply to access it from the CALERIE bio repository — [CALERIE.duke.edu](http://calerie.duke.edu/).
