### ISSUE TITLE
missing data in biomarkers

### ISSUE THREAD

**Issue by lixinmei1235** [dayoonkwon/BioAge#33]
Dear Authors,
When using the kdm_calc function in the BioAge package, I found that when the number of missing biomarkers of an observation is <=2, the corresponding kdm value can be calculated. On what statistical treatment or references is this based? And why not ignore observations that contain any missing values  of these biomarkers? Sincerely waiting for your answer, thank you！

The following code was taken from ‘kdm_calc.R’
dat$kdm = ifelse(BA_nmiss>2,NA,dat$kdm)

**Comment by dayoonkwon** [comment]
The decision to allow calculations of the kdm value when the number of missing biomarkers is two or fewer is based on statistical considerations aimed at maximizing data use while maintaining reliability. When fewer than three biomarkers are missing, it is often still possible to generate a robust kdm estimate using imputation techniques or partial data analysis, which helps to prevent the loss of potentially valuable data.

If you want a complete set of biomarkers without any missing values, I recommend preprocessing your data to include only complete cases before applying the kdm_calc function.
